### ISSUE TITLE
Drop overlay package.xml in favor of upstream's

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2-gbp/fastrtps-release#11]
In https://github.com/eProsima/Fast-DDS/pull/1378 a package.xml was added to Fast-DDS sources. Due to the way the overlay system works that package.xml won't be used until we drop the overlay directory. 

If there are changes that need to be made for release which aren't compatible with the source package.xml they can be made via patching the bloom release branches rather than via the overlay.

**Comment by MiguelCompany** [comment]
@nuclearsandwich Is there anything we should do on the upstream repository for this?

**Comment by nuclearsandwich** [comment]
@MiguelCompany thanks for asking, I don't think so. I remember reviewing the differences between them at one point. I'll revisit this a little later this week and prepare to make the switch. If any changes need to go in the upstream package.xml I'll open PRs for them there.

**Comment by MiguelCompany** [comment]
@nuclearsandwich Would you mind doing a PR to Fast DDS branch `2.1.x` with the changes required to package.xml ?

After that we could then drop the overlay.

**Comment by EduPonz** [comment]
@nuclearsandwich as Foxy and its Fast DDS branch 2.1.x are now EOL, can we close this one?

**Comment by clalancette** [comment]
One thing I think we should do here is to remove the `rolling` patch directory completely, just so we aren't confused by it in the future.  I'll open a PR to do that.
