### ISSUE TITLE
Bloom release fails for foxy, galactic, and rolling

### ISSUE THREAD

**Issue by MiguelCompany** [ros2-gbp/fastrtps-release#24]
I'm trying to bloom-release [v2.1.2](https://github.com/eProsima/Fast-DDS/releases/tag/v2.1.2) into `foxy`, but the process failed trying to apply patches to the debian rules.

I've run `bloom-release --track foxy --ros-distro foxy --edit fastrtps`. I run it with `--edit` so I can change version from `2.1.1` to `:{auto}`.

It fails on `git-bloom-generate -y rosdebian --prefix release/foxy foxy -i 1 --os-name ubuntu` with the following output. What should I do to fix this?

```
==> git-bloom-generate -y rosdebian --prefix release/foxy foxy -i 1 --os-name ubuntu
Generating source debs for the packages: ['fastrtps']
Debian Incremental Version: 1
Debian Distributions: ['focal']
Releasing for rosdistro: foxy

Pre-verifying Debian dependency keys...
Running 'rosdep update'...
All keys are OK

Placing debian template files into 'debian/foxy/fastrtps' branch.
==> Placing templates files in the 'debian' folder.
 [git-bloom-patch import]: 'execute_command' failed to call 'git am --3way /tmp/tmp2nafslqq/*.patch' which had a return code (128):
 [git-bloom-patch import]: ```
Applying: Make sure to set SECURITY=ON when building Fast-RTPS. (#12)
Using index info to reconstruct a base tree...
M       debian/rules.em
Falling back to patching base and 3-way merge...
Auto-merging debian/rules.em
CONFLICT (content): Merge conflict in debian/rules.em
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch' to see the failed patch
Patch failed at 0001 Make sure to set SECURITY=ON when building Fast-RTPS. (#12)
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

 [git-bloom-patch import]: ```
 [git-bloom-patch import]: Failed to apply one or more patches for the 'Command 'git am --3way /tmp/tmp2nafslqq/*.patch' returned non-zero exit status 128.' branch.


>>> Resolve any conflicts and when you have resolved this problem run 'git am --resolved' and then exit the shell using 'exit 0'. <<<
    To abort use 'exit 1'
Traceback (most recent call last):
  File "/usr/bin/git-bloom-generate", line 11, in <module>
    load_entry_point('bloom==0.11.2', 'console_scripts', 'git-bloom-generate')()
  File "/usr/lib/python3/dist-packages/bloom/commands/git/generate.py", line 252, in main
    run_generator(generator, args)
  File "/usr/lib/python3/dist-packages/bloom/commands/git/generate.py", line 172, in run_generator
    try_execute('git-bloom-patch import', msg, import_patches)
  File "/usr/lib/python3/dist-packages/bloom/commands/git/generate.py", line 101, in try_execute
    retcode = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/bloom/logging.py", line 211, in decorated
    return f(*args, **kwds)
  File "/usr/lib/python3/dist-packages/bloom/commands/git/patch/import_cmd.py", line 109, in import_patches
    if 'bash' in os.environ['SHELL']:
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'SHELL'

<== Error running command '['/usr/bin/git-bloom-generate', '-y', 'rosdebian', '--prefix', 'release/foxy', 'foxy', '-i', '1', '--os-name', 'ubuntu']'
Release failed, exiting.
```

**Comment by MiguelCompany** [comment]
Same happens trying to bloom-release v2.3.5 for galactic, and v2.7.1 for rolling

**Comment by clalancette** [comment]
@nuclearsandwich When you get a chance, can you take a look here?

**Comment by nuclearsandwich** [comment]
The error during patch application is something that can occur when bloom templates are updated and there are patches in the specific project release which touch the same content and cause conflicts.

In this case, the work to make testing packages during build optional is conflicting with the additional CMake arguments made to enable security and omit installing examples.

When running interactively (as bloom does by default) the error message will print and drop you into a temporary directory to resolve the conflict. Future releases should not need this step now that the patch has been updated.

Here's the PR for the foxy release of 2.1.2 https://github.com/ros/rosdistro/pull/34221

**Comment by nuclearsandwich** [comment]
Here's the Galactic release: https://github.com/ros/rosdistro/pull/34222

For Rolling, the master branch is being targeted but there's not yet a tag for 2.8.0 should we switch rolling to the 2.7.x branch?

**Comment by MiguelCompany** [comment]
> should we switch rolling to the 2.7.x branch?

I would change the rolling track to 2.7.x, and change it back to master when 2.8.0 is released

**Comment by MiguelCompany** [comment]
@nuclearsandwich I see you have already done a release of 2.7.1 in rolling. Thank you.

For reference, here's the Rolling release: ros/rosdistro#34559

**Comment by nuclearsandwich** [comment]
https://github.com/ros/rosdistro/pull/34601
