### ISSUE TITLE
remove examples from Debian package

### ISSUE THREAD

**Issue by dirk-thomas** [ros2-gbp/fastrtps-release#3]
We have had question about the examples in the past. I think it would be better to not install them - users expect them to be ROS 2 examples which is not the case.

**Comment by mikaelarguedas** [comment]
That's a great improvement. Though people using the fat binaries or building from source (on all platforms) will still have these examples installed at the root of the installspace.
Did we ask eProsima for an option to not install the examples? or to install them to a different location?

**Comment by dirk-thomas** [comment]
> Did we ask eProsima for an option to not install the examples?

Not that I know of. We could create a PR adding a CMake option to skip installing the examples.
